name: Simple test workflow

on:
  push:
    branches: ["main"]

jobs:
  just_run_docker_run:
    runs-on: self-hosted
    steps:
      - name: Run simple docker run hello world
        run: |
          echo Running Docker run to run hello-world program
          docker run -d hello-world
        
